
package com.telebilling.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.telebilling.service.TELEWebService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TELEWebServiceService", targetNamespace = "http://service.telebilling.com/", wsdlLocation = "http://localhost:9002/TELEWebService?wsdl")
public class TELEWebServiceService
    extends Service
{

    private final static URL TELEWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TELEWEBSERVICESERVICE_EXCEPTION;
    private final static QName TELEWEBSERVICESERVICE_QNAME = new QName("http://service.telebilling.com/", "TELEWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9002/TELEWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TELEWEBSERVICESERVICE_WSDL_LOCATION = url;
        TELEWEBSERVICESERVICE_EXCEPTION = e;
    }

    public TELEWebServiceService() {
        super(__getWsdlLocation(), TELEWEBSERVICESERVICE_QNAME);
    }

    public TELEWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TELEWEBSERVICESERVICE_QNAME, features);
    }

    public TELEWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, TELEWEBSERVICESERVICE_QNAME);
    }

    public TELEWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TELEWEBSERVICESERVICE_QNAME, features);
    }

    public TELEWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TELEWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TELEWebService
     */
    @WebEndpoint(name = "TELEWebServicePort")
    public TELEWebService getTELEWebServicePort() {
        return super.getPort(new QName("http://service.telebilling.com/", "TELEWebServicePort"), TELEWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TELEWebService
     */
    @WebEndpoint(name = "TELEWebServicePort")
    public TELEWebService getTELEWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.telebilling.com/", "TELEWebServicePort"), TELEWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TELEWEBSERVICESERVICE_EXCEPTION!= null) {
            throw TELEWEBSERVICESERVICE_EXCEPTION;
        }
        return TELEWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
